(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DMsimp_s_spin0",
  Authors -> {"A. Martini, K. Mawatari, J. Wang, C. Zhang"},
  Institutions -> {"Universite catholique de Louvain, Vrije Universiteit Brussel, Johnnas Gutenberg University of Mainz, Brookhaven National Laboratory"},
  Emails -> {"kentarou.mawatari@vub.ac.be", "cenzhang@bnl.gov"},
  URLs -> "http://feynrules.irmp.ucl.ac.be/wiki/DMsimp/",
  References -> {"O. Mattelaer et al., arXiv:1508.00564", "M. Backovic et al., arXiv:1508.05327", "M. Neubert et al., arXiv:1508.xxxxx"},
  Version -> "1.0",
  Date -> "2015.08.24"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], Xr -> S[4], Xc -> S[5], Xd -> F[13], Y0 -> S[6]};

FR$InteractionOrderPerturbativeExpansion={{DMS, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MXr,
    Indices -> {},
    PropagatorLabel -> "Xr" },

S[5] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MXc,
    Indices -> {},
    PropagatorLabel -> "Xc" },

F[13] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MXd,
    Indices -> {},
    PropagatorLabel -> "Xd" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MY0,
    Indices -> {},
    PropagatorLabel -> "Y0" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[S[7]];
GaugeXi[ S[5] ] = GaugeXi[S[8]];
GaugeXi[ F[13] ] = GaugeXi[F[7]];
GaugeXi[ S[6] ] = GaugeXi[S[9]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MTA[ ___ ] := MTA;
MT[ ___ ] := MT;
MH[ ___ ] := MH;
MXr[ ___ ] := MXr;
MXc[ ___ ] := MXc;
MXd[ ___ ] := MXd;
MY0[ ___ ] := MY0;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{I*gc7, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[1] ] == {{I*gc8, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] ] == {{I*gc9, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[2] , S[2] , S[6] ] == {{(-I)*gc10*gSh2*MH^2, 0}, {I*gc10*gSh1, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , S[6] ] == {{(-I)*gc11*gSh2*MH^2, 0}, {I*gc11*gSh1, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[6] ] == {{(-I)*gc12*gSh2*MH^2, 0}, {I*gc12*gSh1, 0}, {0, 0}, {0, 0}},

C[ S[5] , -S[5] , S[6] ] == {{I*gc13, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[4] , S[4] , S[6] ] == {{I*gc14, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , S[6] , V[1] , V[1] ] == {{((2*I)*EL^2*gSh1)/Lambda, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc17, 0}, {I*gc17, 0}},

C[ S[3] , -S[3] , S[6] , V[1] ] == {{(-I)*gc18, 0}, {I*gc18, 0}, {0, 0}},

C[ S[6] , V[1] , V[1] ] == {{(-I)*gc19*(cw^2*gPb + gPw*sw^2), 0}, {(-I)*gc19*(cw^2*gSb + gSw*sw^2), 0}, {I*gc19*(cw^2*gSb + gSw*sw^2), 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}},

C[ S[6] , V[3] , -V[3] ] == {{(16*I)*gc21*gPw*sw^2, 0}, {(16*I)*gc21*gSw*sw^2, 0}, {(-16*I)*gc21*gSw*sw^2, 0}, {I*EL^2*gc21*gSh1*vev^2, 0}},

C[ S[6] , V[1] , V[2] ] == {{I*gc22*(gPb - gPw), 0}, {I*gc22*(gSb - gSw), 0}, {(-I)*gc22*(gSb - gSw), 0}, {0, 0}},

C[ S[6] , V[2] , V[2] ] == {{(16*I)*cw^2*gc23*sw^2*(cw^2*gPw + gPb*sw^2), 0}, {(16*I)*cw^2*gc23*sw^2*(cw^2*gSw + gSb*sw^2), 0}, {(-16*I)*cw^2*gc23*sw^2*(cw^2*gSw + gSb*sw^2), 0}, {I*EL^2*gc23*gSh1*(cw^2 + sw^2)^2*vev^2, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc25, 0}, {I*gc25, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc31, 0}, {I*gc31, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc39, 0}, {I*gc39, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc43, 0}, {I*gc43, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc45, 0}, {I*gc45, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[13] , F[13] , S[6] ] == {{gPXd + I*gSXd, 0}, {-gPXd + I*gSXd, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc48*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {gc48*SUNF[e3x2, e1x1, e2x1], (GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/(2*aS)}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc49*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc49*SUNF[e1x2, e2x2, e3x2], -(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc49*SUNF[e1x2, e2x2, e3x2], -(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {-(gc49*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {-(gc49*SUNF[e1x2, e2x2, e3x2]), (GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}, {gc49*SUNF[e1x2, e2x2, e3x2], -(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/(2*aS)}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc50*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}, {I*gc50*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc50*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}},

C[ -F[6] , F[3] , -S[3] ] == {{gc51, 0}, {0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc52L, 0}, {gc52R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc53, 0}, {I*gc53, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc54*IndexDelta[e1x2, e2x2], (yt*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/2}, {0, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc55L*IndexDelta[e1x2, e2x2], (yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {gc55R*IndexDelta[e1x2, e2x2], -(yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc56*IndexDelta[e1x2, e2x2], ((-I/2)*yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/Sqrt[2]}, {I*gc56*IndexDelta[e1x2, e2x2], ((-I/2)*yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/Sqrt[2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I/2)*ymt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-I/2)*ymt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ S[2] , -S[3] , S[6] , V[1] , V[3] ] == {{((-I/2)*EL^2*gSh1)/(Lambda*sw), 0}},

C[ -S[3] , S[1] , S[6] , V[1] , V[3] ] == {{-(EL^2*gSh1)/(2*Lambda*sw), 0}},

C[ -S[3] , S[6] , V[1] , V[3] ] == {{-(EL^2*gSh1*vev)/(2*Lambda*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc63, 0}, {I*gc63, 0}},

C[ S[2] , -S[3] , S[6] , V[3] ] == {{(-I)*gc64, 0}, {I*gc64, 0}, {0, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc65, 0}, {gc65, 0}},

C[ -S[3] , S[1] , S[6] , V[3] ] == {{-gc66, 0}, {gc66, 0}, {0, 0}},

C[ -S[3] , S[6] , V[3] ] == {{gc67, 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc68, 0}, {I*gc68, 0}, {I*gc68, 0}, {(-I)*gc68, 0}, {(-I)*gc68, 0}, {I*gc68, 0}},

C[ S[6] , V[1] , V[3] , -V[3] ] == {{I*gc69*gPw, 0}, {I*gc69*gPw, 0}, {I*gc69*gPw, 0}, {(-I)*gc69*gSw, 0}, {I*gc69*gSw, 0}, {I*gc69*gSw, 0}, {(-I)*gc69*gSw, 0}, {(-I)*gc69*gSw, 0}, {I*gc69*gSw, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[2] , S[3] , S[6] , V[1] , -V[3] ] == {{((-I/2)*EL^2*gSh1)/(Lambda*sw), 0}},

C[ S[3] , S[1] , S[6] , V[1] , -V[3] ] == {{(EL^2*gSh1)/(2*Lambda*sw), 0}},

C[ S[3] , S[6] , V[1] , -V[3] ] == {{(EL^2*gSh1*vev)/(2*Lambda*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc75, 0}, {I*gc75, 0}},

C[ S[2] , S[3] , S[6] , -V[3] ] == {{(-I)*gc76, 0}, {I*gc76, 0}, {0, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc77, 0}, {gc77, 0}},

C[ S[3] , S[1] , S[6] , -V[3] ] == {{-gc78, 0}, {gc78, 0}, {0, 0}},

C[ S[3] , S[6] , -V[3] ] == {{gc79, 0}, {0, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[2] , S[2] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*gSh1)/(Lambda*sw^2), 0}},

C[ S[3] , -S[3] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*gSh1)/(Lambda*sw^2), 0}},

C[ S[1] , S[1] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*gSh1)/(Lambda*sw^2), 0}},

C[ S[1] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*gSh1*vev)/(Lambda*sw^2), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc87, 0}, {(-I)*gc87, 0}, {(2*I)*gc87, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc88, 0}, {I*gc88, 0}, {I*gc88, 0}, {(-I)*gc88, 0}, {(-I)*gc88, 0}, {I*gc88, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc89, 0}, {(-I)*gc89, 0}, {(2*I)*gc89, 0}},

C[ S[6] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc90, 0}, {(-I)*gc90, 0}, {(2*I)*gc90, 0}},

C[ S[6] , V[3] , -V[3] , V[2] ] == {{I*gc91*gPw, 0}, {I*gc91*gPw, 0}, {I*gc91*gPw, 0}, {(-I)*gc91*gSw, 0}, {I*gc91*gSw, 0}, {I*gc91*gSw, 0}, {(-I)*gc91*gSw, 0}, {(-I)*gc91*gSw, 0}, {I*gc91*gSw, 0}},

C[ S[6] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc92, 0}, {(-I)*gc92, 0}, {(2*I)*gc92, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc93R, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[6] ] == {{(gc94L*(gPu33 + I*gSu33)*IndexDelta[e1x2, e2x2])/(gPu33 + gSu33), ((gPu33 + I*gSu33)*yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}, {(gc94R*(gPu33 - I*gSu33)*IndexDelta[e1x2, e2x2])/(gPu33 - gSu33), -((gPu33 - I*gSu33)*yt*(FR$deltaZ[{t, t}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2])}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{0, 0}, {gc95R*IndexDelta[e1x2, e2x2], -(yt*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/2}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[3] , -S[3] , S[6] , V[1] , V[2] ] == {{(I*EL^2*gSh1*(cw - sw)*(cw + sw))/(cw*Lambda*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc98, 0}, {gc98, 0}},

C[ S[2] , S[1] , S[6] , V[2] ] == {{-gc99, 0}, {gc99, 0}, {0, 0}},

C[ S[2] , S[6] , V[2] ] == {{gc100, 0}, {0, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc101, 0}, {I*gc101, 0}},

C[ S[3] , -S[3] , S[6] , V[2] ] == {{(-I)*gc102, 0}, {I*gc102, 0}, {0, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ S[2] , -S[3] , S[6] , V[3] , V[2] ] == {{((I/2)*EL^2*gSh1)/(cw*Lambda), 0}},

C[ -S[3] , S[1] , S[6] , V[3] , V[2] ] == {{(EL^2*gSh1)/(2*cw*Lambda), 0}},

C[ -S[3] , S[6] , V[3] , V[2] ] == {{(EL^2*gSh1*vev)/(2*cw*Lambda), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[2] , S[3] , S[6] , -V[3] , V[2] ] == {{((I/2)*EL^2*gSh1)/(cw*Lambda), 0}},

C[ S[3] , S[1] , S[6] , -V[3] , V[2] ] == {{-(EL^2*gSh1)/(2*cw*Lambda), 0}},

C[ S[3] , S[6] , -V[3] , V[2] ] == {{-(EL^2*gSh1*vev)/(2*cw*Lambda), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc113, 0}, {I*gc113, 0}, {I*gc113, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {I*gc117, 0}},

C[ S[2] , S[2] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*gSh1*(cw^2 + sw^2)^2)/(cw^2*Lambda*sw^2), 0}},

C[ S[3] , -S[3] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*gSh1*(cw - sw)^2*(cw + sw)^2)/(cw^2*Lambda*sw^2), 0}},

C[ S[1] , S[1] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*gSh1*(cw^2 + sw^2)^2)/(cw^2*Lambda*sw^2), 0}},

C[ S[1] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*gSh1*(cw^2 + sw^2)^2*vev)/(cw^2*Lambda*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc122, 0}, {(-I)*gc122, 0}, {(2*I)*gc122, 0}},

C[ S[6] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc123, 0}, {I*gc123, 0}, {I*gc123, 0}},

C[ S[6] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc124, 0}, {(-I)*gc124, 0}, {(2*I)*gc124, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc125, 0}, {I*gc125, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc126, 0}, {I*gc126, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc127, 0}, {I*gc127, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc128*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc128*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc129*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc129*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc130*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc130*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc131*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc131*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc132*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc132*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc133*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc133*IndexDelta[e1x2, e2x2], (-I/3)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, 0}, {0, 0}, {0, I*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, 0}, {0, 0}, {0, I*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, 0}, {0, 0}, {0, I*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, 0}, {0, 0}, {0, I*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, 0}, {0, 0}, {0, I*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc139*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc139*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc140*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc140*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc141*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc141*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc142*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc142*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc143*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc143*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc144*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc144*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc145*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x1*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc146*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x2*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc147*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc148*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x1*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc149*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x2*EL*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc150*IndexDelta[e1x2, e2x2], ((I/2)*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc151*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x1]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc152*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x1]*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc153*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x2]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc154*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x2]*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc155, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc156, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc157, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc158, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc159, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc160, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc161L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc161R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc162L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc162R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc163L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc163R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc164L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc164R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc165L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc165R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc166L*IndexDelta[e1x2, e2x2], ((-I/6)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc166R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc167, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc168, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc169, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc170L, 0}, {I*gc170R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc171L, 0}, {I*gc171R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc172L, 0}, {I*gc172R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc7 -> -2*lam*vev,
     gc8 -> -2*lam*vev,
     gc9 -> -6*lam*vev,
     gc10 -> -Lambda^(-1),
     gc11 -> -Lambda^(-1),
     gc12 -> -Lambda^(-1),
     gc13 -> gSXc*MXc,
     gc14 -> gSXr*MXr,
     gc17 -> -EL,
     gc18 -> -((EL*gSh1)/Lambda),
     gc19 -> -4/Lambda,
     gc21 -> 1/(4*Lambda*sw^2),
     gc22 -> (-4*cw*sw)/Lambda,
     gc23 -> 1/(4*cw^2*Lambda*sw^2),
     gc24 -> EL,
     gc25 -> -EL,
     gc27 -> EL,
     gc30 -> -EL,
     gc31 -> -((cw*EL)/sw),
     gc33 -> (cw*EL)/sw,
     gc35 -> -EL,
     gc38 -> EL,
     gc39 -> (cw*EL)/sw,
     gc41 -> -((cw*EL)/sw),
     gc43 -> (cw*EL)/sw,
     gc45 -> -((cw*EL)/sw),
     gc48 -> GS,
     gc49 -> -GS,
     gc50 -> -GS^2,
     gc51 -> ytau,
     gc52L -> -(ytau/Sqrt[2]),
     gc52R -> ytau/Sqrt[2],
     gc53 -> -(ytau/Sqrt[2]),
     gc54 -> yt,
     gc55L -> yt/Sqrt[2],
     gc55R -> -(yt/Sqrt[2]),
     gc56 -> -(yt/Sqrt[2]),
     gc63 -> EL/(2*sw),
     gc64 -> (EL*gSh1)/(2*Lambda*sw),
     gc65 -> -EL/(2*sw),
     gc66 -> -(EL*gSh1)/(2*Lambda*sw),
     gc67 -> (EL*gSh1*vev)/(2*Lambda*sw),
     gc68 -> EL,
     gc69 -> (-4*EL)/Lambda,
     gc75 -> -EL/(2*sw),
     gc76 -> -(EL*gSh1)/(2*Lambda*sw),
     gc77 -> -EL/(2*sw),
     gc78 -> -(EL*gSh1)/(2*Lambda*sw),
     gc79 -> (EL*gSh1*vev)/(2*Lambda*sw),
     gc87 -> -EL^2,
     gc88 -> (cw*EL)/sw,
     gc89 -> EL^2/sw^2,
     gc90 -> (4*EL^2*gSw)/Lambda,
     gc91 -> (-4*cw*EL)/(Lambda*sw),
     gc92 -> (-4*EL^2*gSw)/(Lambda*sw^2),
     gc93R -> -ytau,
     gc94L -> ((gPu33 + gSu33)*yt)/Sqrt[2],
     gc94R -> -(((gPu33 - gSu33)*yt)/Sqrt[2]),
     gc95R -> -yt,
     gc98 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc99 -> -(EL*gSh1*(cw^2 + sw^2))/(2*cw*Lambda*sw),
     gc100 -> (EL*gSh1*(cw^2 + sw^2)*vev)/(2*cw*Lambda*sw),
     gc101 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc102 -> -(EL*gSh1*(cw^2 - sw^2))/(2*cw*Lambda*sw),
     gc113 -> (cw*EL^2)/sw,
     gc117 -> (EL^2*(cw^2 + sw^2)^2*vev)/(2*cw^2*sw^2),
     gc122 -> -((cw^2*EL^2)/sw^2),
     gc123 -> (-4*cw*EL^2*gSw)/(Lambda*sw),
     gc124 -> (4*cw^2*EL^2*gSw)/(Lambda*sw^2),
     gc125 -> -EL,
     gc126 -> -EL,
     gc127 -> -EL,
     gc128 -> (2*EL)/3,
     gc129 -> (2*EL)/3,
     gc130 -> (2*EL)/3,
     gc131 -> -EL/3,
     gc132 -> -EL/3,
     gc133 -> -EL/3,
     gc139 -> GS,
     gc140 -> GS,
     gc141 -> GS,
     gc142 -> GS,
     gc143 -> GS,
     gc144 -> GS,
     gc145 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc146 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc147 -> EL/(Sqrt[2]*sw),
     gc148 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc149 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc150 -> EL/(Sqrt[2]*sw),
     gc151 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc152 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc153 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc154 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc155 -> EL/(Sqrt[2]*sw),
     gc156 -> EL/(Sqrt[2]*sw),
     gc157 -> EL/(Sqrt[2]*sw),
     gc158 -> EL/(Sqrt[2]*sw),
     gc159 -> EL/(Sqrt[2]*sw),
     gc160 -> EL/(Sqrt[2]*sw),
     gc161L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc161R -> (-2*EL*sw)/(3*cw),
     gc162L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc162R -> (-2*EL*sw)/(3*cw),
     gc163L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc163R -> (-2*EL*sw)/(3*cw),
     gc164L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc164R -> (EL*sw)/(3*cw),
     gc165L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc165R -> (EL*sw)/(3*cw),
     gc166L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc166R -> (EL*sw)/(3*cw),
     gc167 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc168 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc169 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc170L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc170R -> (EL*sw)/cw,
     gc171L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc171R -> (EL*sw)/cw,
     gc172L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc172R -> (EL*sw)/cw};

